# Generated by Django 4.1.4 on 2022-12-28 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id_post', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Id do post')),
                ('plataform', models.CharField(choices=[('IG', 'Instagram'), ('FB', 'Facebook'), ('TK', 'Tiktok'), ('YT', 'Youtube')], max_length=2, verbose_name='Rede social')),
                ('post_type', models.CharField(choices=[('ES', 'Estático'), ('CR', 'Carrossel'), ('VD', 'Reel/Video'), ('SH', 'Youtube Shorts')], max_length=2, verbose_name='Formato do post')),
                ('post_link', models.URLField(verbose_name='Link do post')),
                ('post_date', models.DateField(verbose_name='Data de postagem')),
                ('date_input', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro do post no sistema')),
                ('user_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis_app.perfil', verbose_name='Usuário')),
            ],
        ),
    ]
