# Generated by Django 4.1.4 on 2022-12-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collect', models.DateField(verbose_name='Data de referência das métricas')),
                ('reach', models.IntegerField(verbose_name='Quantidade de alcance ou impressões')),
                ('likes', models.IntegerField(verbose_name='Quantidade de likes')),
                ('comments', models.IntegerField(verbose_name='Quantidade de comentários')),
                ('shares', models.IntegerField(blank=True, verbose_name='Quantidade de compartilhamentos')),
                ('saves', models.IntegerField(blank=True, verbose_name='Quantidade de salvos')),
                ('views', models.IntegerField(blank=True, verbose_name='Quantidade de visualizações')),
                ('Engajement', models.IntegerField(blank=True, verbose_name='Engajamento')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='Data de inserção dos dados no sistema')),
            ],
        ),
    ]
