# Generated by Django 4.1.4 on 2022-12-28 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis_app', '0001_initial'),
        ('metricas_app', '0001_initial'),
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetrics',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_app.postinfo'),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='user_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis_app.perfil', verbose_name='Usuário'),
        ),
    ]
