# Generated by Django 4.1.4 on 2022-12-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('imagem', models.ImageField(blank=True, upload_to='relatorios')),
                ('insights', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis_app.perfil')),
            ],
        ),
    ]
